### PR TITLE
Change how extraction works for better concurrency

### LINKED ISSUE #19: Extract performance from a local file or stream is poor
## Bug description

@arybitskyi tested extract performance both from `elastio stream restore` as well as from a local tar file, and reported the findings in [a Google Sheet](https://docs.google.com/spreadsheets/d/1bKnHPYVNakAPfP1qCMMjNYdrdtGeXfoY-yMribCED_o/edit#gid=0) (NOTE: link is internal Elastio only)

## To Reproduce

1. Extract a tar archive either from a local file with `--file`, or from the output of `elastio stream restore` with the `--stdin` argument
2. Note that extract performance is much slower than archive create performance

## Expected behavior

Extract performance should be limited only by the speed of the network connection to S3.  In this case meaning roughly the same as create performance.

## Screenshots

N/A

## Environment

ssstar 0.2.0
EC2 instance type `m5.2xlarge`
Amazon Linux 2

## Additional context

N/A

### PR DESCRIPTION
**Pull request by anelson**
This is a substantial internal refactoring of the `extract` flow which should dramatically increase extract performance in cases which previously saw lower extract performance compared to create performance for the same workload.

It completely rewrites the code that uploads from a tar archive to object storage.  Now the max concurrency configured for the job will always be used, even in cases of multi-part upload or a mix of multi-part and single-part upload.  The code is more complicated, which is why it wasn't initially implemented this way, but the result should be substantially faster writes to object storage.

Helps with #19, however it doesn't actually close it.  Restore performance from `elastio stream restore` is still terrible, but I suspect it might be at least in part due to the `stream restore` command's performance itself.

### CODE REVIEW

**Comment by anelson** [comment]
@NDVas IIRC you were doing the performance testing on `ssstar` most recently.  I'd like your help testing the performance impact of this change.

Please repeat your earlier test with the same objects and data sizes, using the version of `ssstar` from this branch.  To install that version use this command:

```shell
cargo install --git https://github.com/elastio/ssstar.git --branch bug/19-extract-performance --locked ssstar-cli
```

**Comment by anelson** [comment]
Nadia got back to me with her tests:

https://docs.google.com/spreadsheets/d/1NYJUv1Hr_KPKu1k9w2t-zKpAfAt-idKM-dPbuf16b80/edit?usp=sharing

Unfortunately no significant improvement.  That makes no sense!  This new implementation is much more aggressive about concurrent operations.
 
Back to the drawing board...

File: ssstar/src/objstore/mod.rs [hunk 1]
```diff
@@ -142,6 +180,43 @@ pub(crate) trait Bucket: DynClone + std::fmt::Debug + Sync + Send + 'static {
...
+/// `upload_part` and the result will be as if all of those calls were made on a single instance.
+///
+/// `finish` must only be called once across all clones or an error ocurrs.
+#[async_trait::async_trait]
+pub(crate) trait MultipartUploader: DynClone + Sync + Send + 'static {
+    /// Initialize this multi-part upload.
+    ///
+    /// This must be called exactly once, and must be the first call made on this object.
+    /// `upload_part` and `finish` will panic if `init` isn't called first.
+    async fn init(&self) -> Result<()>;
```
Comment (Silverhorn27) [inline ssstar/src/objstore/mod.rs:196]: It is likely logical to use the **State machine** design pattern. If so, the caller will never use the methods in an incorrect order.

File: ssstar/src/objstore/s3.rs [hunk 2]
```diff
@@ -582,6 +584,75 @@ impl S3Bucket {
...
+
+        match size_hint {
+            None => {
+                // Hope that the final size of the object will be small enough that the configured
+                // chunk size is larger than 1/10,000th of the size of the whole object, but assume
+                // it will be large enough that we should use multipart
+                Ok(Some(multipart_chunk_size))
+            }
+            Some(size_hint) => {
+                if size_hint > 5 * (1024 * 1024 * 1024 * 1024u64) {
```
Comment (Silverhorn27) [inline ssstar/src/objstore/s3.rs:611]: What is size `5 * (1024 * 1024 * 1024 * 1024u64)` mean? Why isn't it constant?

File: ssstar/src/objstore/s3.rs [hunk 3]
```diff
@@ -582,6 +584,75 @@ impl S3Bucket {
             key
         }
     }
+
+    /// Compute what the multipart chunk size should be, based on the user's configured chunk size
+    /// but also informed by the estimated size of the object
+    fn compute_multipart_chunk_size(
```
Comment (Silverhorn27) [inline ssstar/src/objstore/s3.rs:590]: In the code I see why an `Option` was used, but the explanation should be also in the doc comment.

**Review by Silverhorn27 — APPROVED** [review]

**Review by vsazhenyuk-softheme — APPROVED** [review]

File: ssstar/src/objstore/s3.rs (hunk 2 above)
Comment (anelson) [reply ssstar/src/objstore/s3.rs:611]: Made it a constant.

File: ssstar/src/objstore/mod.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (anelson) [reply ssstar/src/objstore/mod.rs:196]: Except this is a trait that needs to be object safe, so that pattern isn't practical.

File: ssstar/src/objstore/s3.rs (hunk 3 above)
Comment (anelson) [reply ssstar/src/objstore/s3.rs:590]: Added comment to explain

**Review by Silverhorn27 — APPROVED** [review]
